#!/bin/bash
#
# Run all dotfiles installers.
# Script to install https://github.com/unixorn/zsh-quickstart-kit/blob/master/Readme.md

set -e
set -o pipefail
# set -o xtrace

DEFAULT_HOME_PATH="$HOME"

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

suggest_default_home () {
  printf "\t    $1\n"  
}

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

read_home_path () {
  user " - What is the path for your home folder? (e.g /Users/emoroni)"
  suggest_default_home "Press Enter to use $DEFAULT_HOME_PATH"
  read -e HOME_PATH

  if [[ -z "$HOME_PATH" ]]
  then
    HOME_PATH="$DEFAULT_HOME_PATH"
  fi
}

install_zsh_quickstart () {
  read_home_path

  info "Copying ~/.dotFiles/zsh-quickstart-kit to $HOME_PATH"
  cp -R zsh-quickstart-kit "$HOME_PATH"

  info "Copying ~/.dotFiles/zsh-quickstart-kit to $HOME_PATH"
  cp -R zgen "$HOME_PATH"

  info "Configuring zsh by symlinking the .zshrc, .zsh_aliases and .zsh-completions from this repo into $HOME_PATH"
  cd "$HOME_PATH"/zsh-quickstart-kit
  rm -rf "$HOME_PATH"/zsh
  rm -f "$HOME_PATH"/.zshrc "$HOME_PATH"/.zsh_aliases "$HOME_PATH"/.zsh-completions "$HOME_PATH"/.zgen-setup
  stow --target="$HOME_PATH" zsh
}

if install_zsh_quickstart;
then
  success 'install zsh-quickstart-kit'
else
  fail 'install zsh-quickstart-kit'
  info "If something has failed, please install zsh-quickstart-kit manualy"
  info "refer to: https://github.com/unixorn/zsh-quickstart-kit/blob/master/Readme.md"
fi