#!/bin/bash
#
# Run all dotfiles installers.
# Script to install https://github.com/unixorn/zsh-quickstart-kit/blob/master/Readme.md
# Running ~/.dotFiles/install will create a symlink from ~/.dotFiles/zgen and ~/.dotFiles/zsh-quickstart-kit
# to your home directory, this script will create a symlink from ~/zsh-quickstart-kit/zsh to ~/zsh

set -e
set -o pipefail
# set -o xtrace

DEFAULT_HOME_PATH="$HOME"

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

suggest_default_home () {
  printf "\t    $1\n"  
}

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

read_home_path () {
  user " - What is the path for your home folder? (e.g /Users/emoroni)"
  suggest_default_home "Press Enter to use $DEFAULT_HOME_PATH"
  read -e HOME_PATH

  if [[ -z "$HOME_PATH" ]]
  then
    HOME_PATH="$DEFAULT_HOME_PATH"
  fi
}

install_zsh_quickstart () {
  read_home_path

  cd "$HOME_PATH"/zsh-quickstart-kit
  brew install stow
  stow --target="$HOME_PATH" zsh
}

if install_zsh_quickstart;
then
  success "install zsh-quickstart-kit"
  success "you still have to switch your shell to zsh"
  success "feel free to instal ./fonts and use it on iTerm2"
else
  fail "install zsh-quickstart-kit"
  info "Please take a look at above logs, probably you encountered some conflict during"
  info "Symlinking procress, if so please remove conflicting files and run againg."
  info "refer to: https://github.com/unixorn/zsh-quickstart-kit/blob/master/Readme.md"
fi
